### ISSUE TITLE
Update (or deprecate) to use clean-css@4.

### ISSUE THREAD

**Issue by rwjblue** [shinnn/clean-css-promise#2]
clean-css@4 exposes an API to use promises natively.  It isn't clear to me if this library is still required (downstream things like `broccoli-clean-css` could just use `clean-css@4`'s promise API directly), but if it is it would be nice to get an updated version that works with `clean-css@4` (there are many bugs fixed in 4.x).

**Comment by shinnn** [comment]
I just published clean-css-promise v2.0.0 that uses clean-css v4.x.

@rwjblue, thanks for notifying me of the v4.0.0 release.

**Comment by shinnn** [comment]
Also I published [broccoli-clean-css v2.0.0](https://github.com/shinnn/broccoli-clean-css/releases/tag/v2.0.0).

**Comment by rwjblue** [comment]
Awesome, thank you!
