### ISSUE TITLE
Reconsider failing on warnings.

### ISSUE THREAD

**Issue by cythrawll** [shinnn/clean-css-promise#3]
So we finally got this feature by surprise as ember build snuck this into our build and blew up our build.

We got a pretty frustrating developer experience because of this choice to fail on warnings.

I understand the wish to force people to deal with warnings, I really do. But there are a few places where this isn't the appropriate place to do so.

1. The linting happens on a concatenated css, and doesn't use sourcemaps to report the errors, so error lines are obfuscated.  Therefore it becomes difficult to find the cause of the warning.
2. Since ember build removes tmp during cleanup.  You don't even have a css file you can go into and map the warnings with the line of css code it failed on, making it mapping manually back to the source impossible.
3. Since it runs on compiled css, warnings on upstream vendor css is possible.

In order to troubleshoot what was going on I had to break ember's cleanup process not to clean up tmp. So I could find the css file in that mess, and match the line numbers css-clean was reporting on.  What I found was the following issues I could not fix:  

1. a bug that css-clean doesn't allow single character property names, despite them being allowed for svg: https://github.com/jakubpawlowicz/clean-css/issues/1021. this was in an upstream vendor library.  For this one I had to do an upstream PR to add the correct css-clean ignores so that the build would pass again.
2. extra semicolons in an upstream library generated less file.  Completely benign.

I think until the errors from css-clean can report using sourcemaps, and only fail the build on the immediate projects errors, and continue to just warn on vendor css.  This should go back to reporting warnings.

**Comment by shinnn** [comment]
1. Have a coffee break.
2. Reread the issue description by yourself.
3. Rewrite it with less provocative tone.

**Comment by cythrawll** [comment]
There is no provocative tone intended. Just trying to illustrate how poor the developer experience is.  Please try to lower those shields and have a look again. thank you.

**Comment by shinnn** [comment]
Then this issue is not what I'll deal with.

Thanks for having an interest in this project, anyway.

**Comment by cythrawll** [comment]
Hi, what is the reason for closing this issue?
