### ISSUE TITLE
Update to the latest clean-css due to a security problem with earlier versions.

### ISSUE THREAD

**Issue by mileslane** [shinnn/clean-css-promise#4]
Regular Expression Denial of Service
│ Package       │ clean-css                                                    │ Patched in    │ >=4.1.11

ember-cli > ember-cli-preprocess-registry > broccoli-clean-css > clean-css-promise > clean-css

**Comment by shinnn** [comment]
Did you mention https://www.npmjs.com/advisories/785 ?

**Comment by shinnn** [comment]
No feedback.
